### ISSUE TITLE
build error after version="0.2" on Windows

### ISSUE THREAD

**Issue by cg31** [zonyitoo/libsodium-sys#11]
EVerything was good when version is "0.1".

But after version="0.2", I get this error:
`
   Compiling libsodium-ffi v0.2.0 (Y:\Rust\others\libsodium-ffi\git)
error: couldn't read Y:\Rust\others\libsodium-ffi\git\target\debug\build\libsodium-ffi-f8c6d83e9a968a36\out/bindings.rs: The system cannot find the file specified. (os error 2)
 --> src\lib.rs:6:1
  |
6 | include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
`

vcpkg is installed in X:\dev\vcpkg and updated, and all env are set:

set SODIUM_STATIC=yes
set SODIUM_BUILD_STATIC=yes
set SODIUM_INCLUDE_DIR=X:\dev\vcpkg\installed\x64-windows-static\include
set SODIUM_LIB_DIR=X:\dev\vcpkg\installed\x64-windows-static\lib

**Comment by cg31** [comment]
It is caused by package name, now vcpcg might install "libsodium" as "libsodium::x64-windows-static"

https://github.com/cg31/libsodium-ffi/commit/d6e484a9a13bf6138bad8ea79feded84734a97f5

**Comment by zonyitoo** [comment]
Merged. Released as v0.2.1
