### ISSUE TITLE
How does this differ from the sodiumoxide package?

### ISSUE THREAD

**Issue by burdges** [zonyitoo/libsodium-sys#2]
Just curious since there is no readme really : 

How does this differ from the sodiumoxide package by @dnaq ?

https://github.com/dnaq/sodiumoxide

**Comment by zonyitoo** [comment]
This project is created much earlier than `sodiumoxide`.

I will recommend you to use `sodiumoxide` currently.

**Comment by icasdri** [comment]
Doesn't `sodiumoxide` depend on `libsodium-sys`?
See https://github.com/dnaq/sodiumoxide/blob/master/Cargo.toml#L14

**Comment by icasdri** [comment]
Wait, I think I see now. `sodiumoxide` uses an in-tree `libsodium-sys`. https://github.com/dnaq/sodiumoxide/tree/master/libsodium-sys

**Comment by zonyitoo** [comment]
Yes, indeed.
