### ISSUE TITLE
replace the in-tree libsodium-sys from sodiumoxide on crates.io?

### ISSUE THREAD

**Issue by oconnor663** [zonyitoo/libsodium-sys#3]
It looks like the bindings here are more complete than the in-tree version of this library that sodiumoxide is publishing. (In particular I went looking for the secretbox "easy" functions and found them here but not there.) Of course it doesn't really matter what sodiumoxide uses under the hood, but since the crates.io package is currently published from there, it would be nice to get the more complete implementation uploaded. Would it make sense for sodiumoxide to take an import from here? I'm mostly curious whether @zonyitoo and @dnaq already have a plan for something.

**Comment by zonyitoo** [comment]
Well, it depends on @dnaq . This repo was built far more earlier than `sodiumoxide`, but `sodiumoxide` has more complete Rust API encapsulation. I hope this `libsodium-sys` could be merged into `sodiumoxide`, do you agree? @dnaq .
