### ISSUE TITLE
crypto_stream_aes128ctr is going away

### ISSUE THREAD

**Issue by jedisct1** [zonyitoo/libsodium-sys#5]
Hi @zonyitoo !

Just to let you know that the `crypto_stream_aes128ctr*()` functions, that have been deprecated for a long time, have been removed.

In order to avoid linking errors when libsodium 1.0.15 is released, maybe you should remove them from libsodium-sys as well.

Cheers,

-Frank.

**Comment by zonyitoo** [comment]
Ah! Thanks for reminding. I will remove it immediately.

**Comment by zonyitoo** [comment]
Removed in d197a00b091ca0b73bf5b23747496e98dddd52e0
